# fly.toml file generated for tsoha2023-restaurant-finder on 2023-04-02T19:35:15+03:00

app = "tsoha2023-restaurant-finder"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
